name: Build and publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: "25.05"

jobs:
  build-and-push:
    strategy:
      fail-fast: true
      matrix:
        arch:
          - label: ubuntu-24.04
            tag: linux-amd64
          - label: ubuntu-24.04-arm
            tag: linux-arm64
    runs-on: ${{ matrix.arch.label }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build-and-push
        run: |
          # Build image
          nix build .#default
          # Push images
          skopeo copy --retry-times=3 docker-archive:result docker://${IMAGE_NAME}:${IMAGE_TAG}-\${{ matrix.arch.tag }}

  push-manifset:
    runs-on: ubuntu-24.04
    needs:
      - build-and-push
    permissions:
      packages: write
    steps:
      - name: Install manifest-tool
        run: |
          git clone --branch v2.2.0 --depth=1 https://github.com/estesp/manifest-tool
          make -C manifest-tool binary
          sudo mkdir -p /usr/local/bin
          sudo cp "${PWD}/manifest-tool/manifest-tool" /usr/local/bin
          rm -rf manifest-tool

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest image
        run: |
          manifest-tool push from-args \
            --platforms linux/amd64,linux/arm64 \
            --template ${IMAGE_NAME}:${IMAGE_TAG}-OS-ARCH \
            --target ${IMAGE_NAME}:${IMAGE_TAG}
